/*
--- Day 6: Signals and Noise ---

Of course, that would be the message - if you hadn't agreed to use a modified repetition code instead.

In this modified code, the sender instead transmits what looks like random data, but for each character,
the character they actually want to send is slightly less likely than the others.
Even after signal-jamming noise, you can look at the letter distributions in each column and choose the least
common letter to reconstruct the original message.

In the above example, the least common character in the first column is a; in the second, d, and so on.
Repeating this process for the remaining characters produces the original message, advent.

Given the recording in your puzzle input and this new decoding methodology,
what is the original message that Santa is trying to send?
*/

namespace AdventOfCodeDay6Part1 {

    class SignalsAndNoise {

        private _input: Array<string>;

        public constructor(input: Array<string>) {
            this._input = this.swapStrings(input);
        };

        public getMessage(): string {
            let message: string = "";

            for (let line of this._input) {
                message += this.getMinFrequency(line);
            }

            return message;
        }

        private swapStrings(input: Array<string>): Array<string> {
            let newInput: Array<string> = [];

            for (let line of input) {
                for (let i: number = 0; i < line.length; i++) {
                    if (!newInput[i]) {
                        newInput[i] = "";
                    }
                    newInput[i] += line[i];
                }
            }
            return newInput;
        }

        private getMinFrequency(str: string): string {
            let frequency: Object = {};
            let arr: Array<string> = str.split("");
            let value: string;

            for (value of arr) {
                if (value in frequency) {
                    frequency[value]++;
                } else {
                    frequency[value] = 1;
                }
            }

            let maxFrequency: string = arr[0];
            for (let a in frequency) {
                if (frequency[a] < frequency[maxFrequency]) {
                    maxFrequency = a;
                }
            }
            return maxFrequency;
        }
    }

    /**
     * TESTS
     */
    interface ITestInputsObject {
        "input": Array<string>;
        "result": string;
    }

    let testInputs: Array<ITestInputsObject> = [
        {
            "input": [
                "eedadn",
                "drvtee",
                "eandsr",
                "raavrd",
                "atevrs",
                "tsrnev",
                "sdttsa",
                "rasrtv",
                "nssdts",
                "ntnada",
                "svetve",
                "tesnvt",
                "vntsnd",
                "vrdear",
                "dvrsen",
                "enarar"
            ],
            "result": "advent"
        }
    ];

    for (let testInput of testInputs) {
        let codeTest: SignalsAndNoise = new SignalsAndNoise(testInput.input);
        let test: string = codeTest.getMessage();

        if (test !== testInput.result) {
            throw "Test failed: (" + typeof test + ")" + test +
            " !== (" + typeof testInput.result + ")" + testInput.result;
        }
    }

    /**
     * SOLUTION
     */
    let input: Array<string> = [
        "tmcezlum",
        "afzwmyrz",
        "ollxkaqs",
        "oqvdutkr",
        "ufzmsidi",
        "wnidhqow",
        "efgwivmh",
        "endrsvkk",
        "nraaoczx",
        "yghmfumn",
        "fcwrdzyt",
        "qbbejygt",
        "ohrzbtul",
        "lmrarckg",
        "frzhozsk",
        "ahvqozmk",
        "cnoxuqjm",
        "njudcxbx",
        "xjeohiim",
        "sygfjxcx",
        "fbmchcaa",
        "qqggrcwq",
        "vbcgurox",
        "eujzkdmh",
        "kbpinltk",
        "posxqzam",
        "rojnpogl",
        "zvhruwqw",
        "hvbrxcky",
        "iqifiukd",
        "xetwaptt",
        "qvksnzoe",
        "nulslfja",
        "tphqwfte",
        "ddencvfp",
        "nhabbwcl",
        "jefzkclw",
        "txstxeio",
        "yaaqxpdp",
        "efewzeqa",
        "teapznjk",
        "jylnjhnf",
        "jumelmrz",
        "ziarkfwo",
        "vklsvaca",
        "uoyzpkbn",
        "oovggzkn",
        "ajvmcuon",
        "gkztjkss",
        "qnwohfwg",
        "kxwtvaez",
        "jwavozvo",
        "qgqbbaoc",
        "xzdepoxu",
        "kbxhekyv",
        "ceuqobnx",
        "qlrejrjz",
        "fvknhyqb",
        "tfwsmaei",
        "ofpzikkg",
        "xggckiou",
        "avcoljdv",
        "vhzjtrwv",
        "dyqnywkg",
        "udobaedh",
        "gncyxisz",
        "oedldehj",
        "ssmyewfv",
        "ciaphyxw",
        "fhizpimr",
        "bjyeqyzh",
        "owjojbzf",
        "skdfqaeq",
        "ubspxbix",
        "truvdgua",
        "ttvftscb",
        "qjyxodqz",
        "cakskune",
        "okojmtim",
        "rvrhaprz",
        "iezxilxh",
        "yalqlefr",
        "rxygadto",
        "hdszdagc",
        "srqhzltw",
        "vuinwxvi",
        "jcunlnmn",
        "jxolxqid",
        "mnnjrghb",
        "jogafqpd",
        "ixdlwxwj",
        "sttkgdyk",
        "iqfeawey",
        "zdlukwnn",
        "odghxddl",
        "eoflpjdw",
        "haketaof",
        "ylkfukna",
        "pdwemhut",
        "ryyhsryr",
        "iapyhpba",
        "wtgsqrtt",
        "hctctzdi",
        "ulnuyuex",
        "bpxpdeqb",
        "itbourhl",
        "dztqwptk",
        "gmmsltml",
        "evnhvtiy",
        "asjexlfo",
        "sgxejmmg",
        "qxbhjpmp",
        "prauglcy",
        "bulipmjg",
        "xjrkceql",
        "utehzgxa",
        "ltvfsdrj",
        "lnyazzkp",
        "ddnndirm",
        "bddvibpq",
        "ajxjxdls",
        "uidqyood",
        "cjqffbdm",
        "nzonwmsr",
        "zmcesyao",
        "wvfwtwuc",
        "pwuqzzvg",
        "eciaebxq",
        "vxbuvava",
        "yhalnneq",
        "pejiyegy",
        "tsopxjfn",
        "ggzatxrg",
        "lgnpyiko",
        "einylipk",
        "cwtgfpza",
        "niddiicg",
        "ctqbwhzb",
        "mzpgsons",
        "aqaxajai",
        "fkwufqgn",
        "dglewfob",
        "xoqdxsnr",
        "blxnybat",
        "bohqqthr",
        "qanfhczt",
        "gkpxjfrb",
        "zmewqucy",
        "atuodurb",
        "suiitdqe",
        "usywjzqc",
        "voltqnvd",
        "ppstzuzb",
        "ncxkbwul",
        "hgivkyyq",
        "bldyxpov",
        "yvjbraai",
        "fhqawceq",
        "nrmjvhnh",
        "kpwxogac",
        "trtzfnkp",
        "pczcsgns",
        "rfjdromo",
        "uncmnnjj",
        "eordqsju",
        "rhvpcncs",
        "hrokpyig",
        "bkszmpef",
        "krugmwkb",
        "syvtsdek",
        "vigizldv",
        "vldwtfmv",
        "ckcbqkrf",
        "dtvjipcw",
        "ampjmdpd",
        "kcirijwv",
        "zzufovbr",
        "olexgnqh",
        "llxddfsh",
        "wfnnkivb",
        "dzvcoxpi",
        "wpcwuqoc",
        "nejgfqvm",
        "mgbjcbst",
        "uglwuejg",
        "rwfcpnpp",
        "dbfycvwm",
        "hisynlnw",
        "gglqswni",
        "wpmiixuf",
        "rqbfxlef",
        "lsupxzeu",
        "uqrzsowl",
        "xqmgmnyk",
        "gzdfdbtb",
        "aoyujvtz",
        "zmhsbsde",
        "xnmsgyvk",
        "gszwzotk",
        "fkbphiti",
        "lffmpdda",
        "plotuwbi",
        "hakfuxeb",
        "cpqzjdjb",
        "foqwhfis",
        "ctevnjly",
        "bbnuoohx",
        "zjndqgbv",
        "ftmrakmg",
        "yphljbse",
        "vcmmtout",
        "ishcbwpn",
        "oysaacfd",
        "upawmrwj",
        "cexlaadr",
        "cezsoibf",
        "yydnylal",
        "mieypczr",
        "ltbuvmfu",
        "ekumekic",
        "krbiejuo",
        "cyweeeht",
        "lugkftlh",
        "pohkdvai",
        "xgoxbacm",
        "ingicfit",
        "dclavjqp",
        "dnzgfbrc",
        "jssnhcfu",
        "txykgvhl",
        "uwvgyzgz",
        "jecfzcoi",
        "yaktumqx",
        "oqehhika",
        "voqmtwam",
        "wchhskdh",
        "kxjzeygs",
        "krfjungf",
        "iqamjkgh",
        "ajaxlbcr",
        "mfrdjjwz",
        "jvqfkkjt",
        "mupueoje",
        "ozvctxzd",
        "qneodvvw",
        "zisckhyc",
        "yxgudchh",
        "oapmbpbc",
        "pyizuqnn",
        "ttnblbho",
        "xdpiahgx",
        "lyerpyzv",
        "dzslbegp",
        "fvujdszc",
        "qhuhvkej",
        "wxktwmez",
        "irrqradv",
        "xtbqoxyg",
        "nhlrfrgy",
        "gocvpvlp",
        "bwybesby",
        "rvewprlo",
        "elwmmcos",
        "fertmhyj",
        "qhxooqtq",
        "gzdaipgn",
        "yqfmniyt",
        "gornoejg",
        "wqgsxzys",
        "kxqaletd",
        "ikuvaeft",
        "essiqowb",
        "ymohhvfu",
        "kzjynqhe",
        "ooxnssfp",
        "hpnozozp",
        "kdxkokxe",
        "rwredkrn",
        "znmrmswj",
        "svtkdsuu",
        "ibjqwhwi",
        "mknydjrv",
        "opchsgmr",
        "tbyvuatt",
        "igevmbpk",
        "expjknbc",
        "kzboboox",
        "usoxsikr",
        "fizzvucq",
        "rvjomwnd",
        "sgfcwqdl",
        "ocacgxpj",
        "mropbfvf",
        "xexycbuo",
        "qngxnnud",
        "itmenmlm",
        "dyaqaifs",
        "jwgtqejq",
        "eyeaavrj",
        "vwyjauhk",
        "hqajvjkh",
        "ddvhuacy",
        "gjgrgtll",
        "mgawuelx",
        "lmdgzggf",
        "pbtgkvxc",
        "svwklnwu",
        "kvtsovnm",
        "oybxcuqk",
        "ufwkjtlj",
        "xkrgfyad",
        "kdgdjzqp",
        "iqdgesbu",
        "mxpocjsl",
        "rmwvihpw",
        "bpbftisr",
        "kgtgxxqw",
        "ypwjafxu",
        "hihxitsz",
        "lnntwahr",
        "ssecoqkz",
        "ynktphtd",
        "skwfmfpw",
        "bihrglvz",
        "xzkjkgjm",
        "cuozrxqe",
        "qmcfrurm",
        "tphowbli",
        "zvzwyhrv",
        "vzlfbuor",
        "vblsrrba",
        "lakiynlc",
        "afomthrw",
        "rbgtoyfq",
        "ahkqljen",
        "gamoerak",
        "wumjelwi",
        "vqimktjy",
        "levvfcsq",
        "euwrqnjp",
        "fapllntx",
        "vyzlxslf",
        "rwhcbrvz",
        "txpficpp",
        "mbwpimjr",
        "zohppwog",
        "zdrsdecc",
        "uaxqlvsh",
        "ykerbsdc",
        "aecktaff",
        "wrtdufue",
        "gykyrwcv",
        "sesrvnsp",
        "hmopnqyy",
        "tfuulvec",
        "jdokvsfw",
        "jwkhzpaf",
        "mjvzffxn",
        "pctkfrtb",
        "wfiwcoxg",
        "qodzwvbg",
        "brcaggnu",
        "jjjrrtiu",
        "ktkobacy",
        "nahinlmj",
        "nszbvcmi",
        "nfvbldhe",
        "tjweqfgt",
        "crabmuxk",
        "affxwlpf",
        "mpominpv",
        "yufjtaaa",
        "hzzhmsyx",
        "plwdkozp",
        "ozbgwwvd",
        "pplerubj",
        "wzumeuqo",
        "ksynbxaf",
        "yxeircsj",
        "gaqlykne",
        "irsltmrz",
        "jifivecj",
        "vhwsstkq",
        "mjiiiuab",
        "nkimvhvg",
        "memuhxrh",
        "tjvbzypn",
        "glebcdpn",
        "zrmcpufo",
        "imxlujrn",
        "acftqbcf",
        "symmrhuj",
        "lqkrybxd",
        "jsyxqzqt",
        "xbqjvjxl",
        "qwqsvysm",
        "ddjypobl",
        "rwxyfjby",
        "wpoiklyi",
        "eiftosiu",
        "cabwkqhx",
        "yxtbhlxo",
        "heismnzr",
        "yaduhfgm",
        "nghplvvs",
        "lwukrqdx",
        "ifjqghtk",
        "qclffqxm",
        "cuszvrgk",
        "ocshztws",
        "hipeodcu",
        "qnbgnllz",
        "qsuogdmr",
        "eusogkvt",
        "rddealkr",
        "fjrrvsco",
        "nugopflj",
        "bhgbdkxs",
        "fthcqpao",
        "tkdvyegv",
        "tbvpgueq",
        "ahfagxlm",
        "cipkqfxj",
        "vqqcipuc",
        "mugdchdl",
        "wwjpnife",
        "purpypnv",
        "cqzunigd",
        "nlnvjhbd",
        "hhiqrzod",
        "fwjhmdij",
        "wkpvakif",
        "bjrytvwo",
        "uosbgqjb",
        "bdmfzjcy",
        "dxlqldzl",
        "akqbtwvs",
        "wbxschlg",
        "mrzksrhs",
        "jmvueuih",
        "ebxpjnhp",
        "llsogwyw",
        "peyzimia",
        "mufdkyny",
        "dlvxntre",
        "dyfyazrx",
        "aarkcrwe",
        "qqacegoh",
        "rbiqykai",
        "tbnkymsk",
        "ebtsieby",
        "uhyjeeba",
        "ahpywtnx",
        "gyvacpuf",
        "frcyslud",
        "mwwnxofu",
        "jzyabbkj",
        "cctdoztv",
        "jztmavpd",
        "sacgyoii",
        "gnqiydic",
        "ggdrerzq",
        "lduphshn",
        "hctmpgih",
        "kqabzyjt",
        "ppkztsay",
        "pnusnowm",
        "ulyvxfkp",
        "vmlapyyt",
        "zifxarmp",
        "vnpzxhjb",
        "raewumao",
        "wejyiymi",
        "gjbdfjzy",
        "bxhlwziy",
        "rsqlgthf",
        "xtkaltqu",
        "smiarmpw",
        "xdypfzem",
        "yleuggnb",
        "wgphfsve",
        "xgqmyqhq",
        "iyfrymtc",
        "bwhjkhfl",
        "aftctjug",
        "seibsuof",
        "ngcdnmxw",
        "ltxyudxa",
        "xpwqkgdl",
        "hagwixkv",
        "lhtlmxqw",
        "dcineqxs",
        "nzdrjynu",
        "vmytcguy",
        "ymsuzmox",
        "lkzvgcgh",
        "dfjgzjdn",
        "rvmgejgk",
        "dcxdrgpz",
        "bhjsceuv",
        "nhpllxmo",
        "gkotvtsu",
        "uubvdkjg",
        "zjnerxhq",
        "butazmez",
        "szzvqyzs",
        "fpchqsei",
        "xfsvriyr",
        "vxodutyh",
        "zsilhmba",
        "rvacqpwj",
        "hjewdrtx",
        "bylcpgfs",
        "qtntvgfq",
        "ioqldhye",
        "wlrbwapp",
        "nlptloss",
        "znnybfvl",
        "einvacbu",
        "kyziepsr",
        "fthuwmlv",
        "pmkbhvdn",
        "xuxngboe",
        "tpoinkzc",
        "zwbnhlwp",
        "usuusbin",
        "jiulcmsq",
        "elcusgvu",
        "frclhdyo",
        "pvmirlch",
        "jvrjfxmb",
        "sxmtcrsw",
        "ccfkmgmw",
        "mdnibgld",
        "idmojsza",
        "hsjvyoua",
        "smhwbpax",
        "pgcozahq",
        "dstdnwle",
        "aiikfrxt",
        "kmbnsppa",
        "wsxcbwze",
        "hqyunies",
        "mfrxeqyw",
        "zikpwtqz",
        "zckxtclz"
    ];

    let solution: SignalsAndNoise = new SignalsAndNoise(input);
    console.log("Message: ", solution.getMessage());
}
